Description: >
  Okpara Kenneth Chinonso| Udacity 2022
  AWS-CloudFormation script to create a IAM policy for my S3 Bucket

#/////////////////// Parameters #/////////////////////////////
Parameters:
  ProjectName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: UdagramApp

#////////////////////////////// Resources #///////////////////////////////
Resources:
  RoleForS3Bucket:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ec2.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'

  RoleForS3BucketProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: '/'
      Roles:
        - Ref: 'RoleForS3Bucket'

Outputs:
  RoleForS3Bucket:
    Description: 'Allow EC2 instances to manage Web App S3'
    Value: !Ref RoleForS3BucketProfile
    Export:
      Name: !Sub ${ProjectName}-IAM-NAME
  IAMRoleWebAppArn:
    Description: Iam Instance Profile Arn
    Value: !GetAtt RoleForS3Bucket.Arn
    Export:
      Name: !Sub ${ProjectName}-IAM-ARN
